-- Taller v2: número visible, fotos de ingreso, tareas por parte, tramos de tiempo
-- por mecánico y funciones atómicas para cronómetro y aprobación de repuestos.

-- ── Órdenes ────────────────────────────────────────────────────────────────
ALTER TABLE public.ordenes_taller
  ADD COLUMN IF NOT EXISTS numero integer GENERATED BY DEFAULT AS IDENTITY,
  ADD COLUMN IF NOT EXISTS kilometraje integer,
  ADD COLUMN IF NOT EXISTS fotos text[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS lista_at timestamptz,
  ADD COLUMN IF NOT EXISTS entregada_at timestamptz;

CREATE UNIQUE INDEX IF NOT EXISTS ordenes_taller_numero_key ON public.ordenes_taller (numero);
CREATE INDEX IF NOT EXISTS idx_ordenes_taller_placa ON public.ordenes_taller (upper(placa));

ALTER TABLE public.ordenes_taller DROP CONSTRAINT IF EXISTS ordenes_taller_kilometraje_check;
ALTER TABLE public.ordenes_taller
  ADD CONSTRAINT ordenes_taller_kilometraje_check CHECK (kilometraje IS NULL OR kilometraje >= 0);

-- El estado de repuestos se deriva de sus filas; la orden solo guarda el avance del trabajo.
UPDATE public.ordenes_taller
SET estado = 'en_reparacion'
WHERE estado IN ('esperando_repuestos', 'repuestos_rechazados');

ALTER TABLE public.ordenes_taller DROP CONSTRAINT IF EXISTS ordenes_taller_estado_check;
ALTER TABLE public.ordenes_taller
  ADD CONSTRAINT ordenes_taller_estado_check
  CHECK (estado IN ('recibida', 'en_reparacion', 'lista', 'entregada', 'cancelada'));

-- ── Tareas por parte de la moto (varias por parte) ─────────────────────────
ALTER TABLE public.orden_taller_zonas
  DROP CONSTRAINT IF EXISTS orden_taller_zonas_orden_id_zona_key;

ALTER TABLE public.orden_taller_zonas
  ADD COLUMN IF NOT EXISTS hecho boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS hecho_at timestamptz,
  ADD COLUMN IF NOT EXISTS created_by text;

-- ── Repuestos: parte asociada, pedidos fuera de inventario y auditoría ─────
ALTER TABLE public.orden_taller_repuestos
  ALTER COLUMN producto_id DROP NOT NULL,
  ADD COLUMN IF NOT EXISTS zona text,
  ADD COLUMN IF NOT EXISTS descripcion text,
  ADD COLUMN IF NOT EXISTS rechazado_por text,
  ADD COLUMN IF NOT EXISTS rechazado_at timestamptz;

ALTER TABLE public.orden_taller_repuestos
  DROP CONSTRAINT IF EXISTS orden_taller_repuestos_producto_o_descripcion;
ALTER TABLE public.orden_taller_repuestos
  ADD CONSTRAINT orden_taller_repuestos_producto_o_descripcion
  CHECK (producto_id IS NOT NULL OR nullif(trim(descripcion), '') IS NOT NULL);

-- ── Tramos de tiempo (fuente de verdad para medir a cada mecánico) ─────────
CREATE TABLE IF NOT EXISTS public.orden_taller_tiempos (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  orden_id uuid NOT NULL REFERENCES public.ordenes_taller(id) ON DELETE CASCADE,
  mecanico_id integer REFERENCES public.mecanicos(id) ON DELETE SET NULL,
  inicio timestamptz NOT NULL DEFAULT now(),
  fin timestamptz,
  CHECK (fin IS NULL OR fin >= inicio)
);

CREATE UNIQUE INDEX IF NOT EXISTS orden_taller_tiempos_un_tramo_abierto
  ON public.orden_taller_tiempos (orden_id) WHERE fin IS NULL;
CREATE INDEX IF NOT EXISTS idx_orden_taller_tiempos_mecanico
  ON public.orden_taller_tiempos (mecanico_id, inicio DESC);
CREATE INDEX IF NOT EXISTS idx_orden_taller_tiempos_orden
  ON public.orden_taller_tiempos (orden_id);

INSERT INTO public.orden_taller_tiempos (orden_id, mecanico_id, inicio, fin)
SELECT o.id, o.mecanico_id,
       now() - make_interval(secs => o.segundos_acumulados), now()
FROM public.ordenes_taller o
WHERE o.segundos_acumulados > 0
  AND NOT EXISTS (SELECT 1 FROM public.orden_taller_tiempos t WHERE t.orden_id = o.id);

UPDATE public.ordenes_taller SET timer_running = false, timer_started_at = NULL
WHERE timer_running
  AND NOT EXISTS (
    SELECT 1 FROM public.orden_taller_tiempos t WHERE t.orden_id = ordenes_taller.id AND t.fin IS NULL
  );

-- ── Cronómetro ─────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.taller_timer_stop(p_orden_id uuid)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
  v_secs integer;
BEGIN
  UPDATE public.orden_taller_tiempos
  SET fin = now()
  WHERE orden_id = p_orden_id AND fin IS NULL
  RETURNING greatest(0, floor(extract(epoch FROM (fin - inicio))))::integer INTO v_secs;

  UPDATE public.ordenes_taller
  SET timer_running = false,
      timer_started_at = NULL,
      segundos_acumulados = segundos_acumulados + coalesce(v_secs, 0)
  WHERE id = p_orden_id;
END;
$$;

-- Devuelve cuántas otras motos del mismo mecánico se pausaron.
CREATE OR REPLACE FUNCTION public.taller_timer_start(p_orden_id uuid)
RETURNS integer
LANGUAGE plpgsql
AS $$
DECLARE
  v_orden record;
  v_otra uuid;
  v_pausadas integer := 0;
BEGIN
  SELECT id, mecanico_id, estado, timer_running INTO v_orden
  FROM public.ordenes_taller WHERE id = p_orden_id FOR UPDATE;

  IF NOT FOUND THEN RAISE EXCEPTION 'No encontramos esta moto.'; END IF;
  IF v_orden.estado IN ('entregada', 'cancelada') THEN
    RAISE EXCEPTION 'Esta moto ya salió del taller.';
  END IF;
  IF v_orden.mecanico_id IS NULL THEN
    RAISE EXCEPTION 'Primero elige quién arregla la moto.';
  END IF;
  IF v_orden.timer_running THEN RETURN 0; END IF;

  -- Un mecánico trabaja una sola moto a la vez.
  FOR v_otra IN
    SELECT id FROM public.ordenes_taller
    WHERE mecanico_id = v_orden.mecanico_id AND timer_running AND id <> p_orden_id
  LOOP
    PERFORM public.taller_timer_stop(v_otra);
    v_pausadas := v_pausadas + 1;
  END LOOP;

  INSERT INTO public.orden_taller_tiempos (orden_id, mecanico_id)
  VALUES (p_orden_id, v_orden.mecanico_id);

  UPDATE public.ordenes_taller
  SET timer_running = true,
      timer_started_at = now(),
      estado = CASE WHEN estado IN ('recibida', 'lista') THEN 'en_reparacion' ELSE estado END,
      lista_at = CASE WHEN estado = 'lista' THEN NULL ELSE lista_at END
  WHERE id = p_orden_id;

  RETURN v_pausadas;
END;
$$;

-- Cambiar de mecánico cierra el tramo del anterior y, si corría, abre uno al nuevo.
CREATE OR REPLACE FUNCTION public.taller_asignar_mecanico(p_orden_id uuid, p_mecanico_id integer)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
  v_orden record;
BEGIN
  SELECT id, mecanico_id, estado, timer_running INTO v_orden
  FROM public.ordenes_taller WHERE id = p_orden_id FOR UPDATE;

  IF NOT FOUND THEN RAISE EXCEPTION 'No encontramos esta moto.'; END IF;
  IF v_orden.estado IN ('entregada', 'cancelada') THEN
    RAISE EXCEPTION 'Esta moto ya salió del taller.';
  END IF;
  IF v_orden.mecanico_id IS NOT DISTINCT FROM p_mecanico_id THEN RETURN; END IF;

  IF v_orden.timer_running THEN
    PERFORM public.taller_timer_stop(p_orden_id);
  END IF;

  UPDATE public.ordenes_taller SET mecanico_id = p_mecanico_id WHERE id = p_orden_id;

  IF v_orden.timer_running AND p_mecanico_id IS NOT NULL THEN
    PERFORM public.taller_timer_start(p_orden_id);
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.taller_cambiar_estado(p_orden_id uuid, p_estado text)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
  v_actual text;
BEGIN
  SELECT estado INTO v_actual FROM public.ordenes_taller WHERE id = p_orden_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'No encontramos esta moto.'; END IF;
  IF v_actual IN ('entregada', 'cancelada') THEN
    RAISE EXCEPTION 'Esta moto ya salió del taller.';
  END IF;
  IF p_estado NOT IN ('en_reparacion', 'lista', 'entregada', 'cancelada') THEN
    RAISE EXCEPTION 'Estado no válido: %', p_estado;
  END IF;

  IF p_estado IN ('lista', 'entregada', 'cancelada') THEN
    PERFORM public.taller_timer_stop(p_orden_id);
  END IF;

  IF p_estado = 'cancelada' THEN
    UPDATE public.orden_taller_repuestos
    SET estado = 'rechazado', motivo_rechazo = 'Orden cancelada', rechazado_at = now()
    WHERE orden_id = p_orden_id AND estado = 'solicitado';
  END IF;

  UPDATE public.ordenes_taller
  SET estado = p_estado,
      lista_at = CASE
        WHEN p_estado = 'lista' THEN now()
        WHEN p_estado = 'en_reparacion' THEN NULL
        ELSE lista_at
      END,
      entregada_at = CASE WHEN p_estado = 'entregada' THEN now() ELSE entregada_at END
  WHERE id = p_orden_id;
END;
$$;

-- ── Repuestos: aprobar descuenta inventario en la misma transacción ────────
CREATE OR REPLACE FUNCTION public.taller_aprobar_repuesto(p_repuesto_id uuid, p_por text)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
  r record;
  v_stock integer;
  v_costo integer;
  v_nombre text;
BEGIN
  SELECT * INTO r FROM public.orden_taller_repuestos WHERE id = p_repuesto_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Este pedido ya no existe.'; END IF;
  IF r.estado = 'aprobado' THEN RETURN; END IF;
  IF r.estado = 'rechazado' THEN
    RAISE EXCEPTION 'Este pedido fue rechazado. El mecánico debe corregirlo.';
  END IF;

  IF r.producto_id IS NOT NULL THEN
    SELECT stock, costo, nombre INTO v_stock, v_costo, v_nombre
    FROM public.inventario_productos WHERE id = r.producto_id FOR UPDATE;
    IF coalesce(v_stock, 0) < r.cantidad THEN
      RAISE EXCEPTION 'No alcanza: hay % de "%" y piden %.', coalesce(v_stock, 0), v_nombre, r.cantidad;
    END IF;
    PERFORM public.descontar_stock_fifo_ubicaciones(r.producto_id, r.cantidad);
  END IF;

  UPDATE public.orden_taller_repuestos
  SET estado = 'aprobado',
      costo_unitario = v_costo,
      aprobado_por = p_por,
      aprobado_at = now(),
      motivo_rechazo = NULL,
      rechazado_por = NULL,
      rechazado_at = NULL
  WHERE id = p_repuesto_id;
END;
$$;

-- Deshacer una decisión de Sebastian: devuelve inventario si ya se había descontado.
CREATE OR REPLACE FUNCTION public.taller_revertir_repuesto(p_repuesto_id uuid)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
  r record;
BEGIN
  SELECT * INTO r FROM public.orden_taller_repuestos WHERE id = p_repuesto_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Este pedido ya no existe.'; END IF;

  IF r.estado = 'aprobado' AND r.producto_id IS NOT NULL THEN
    PERFORM public.devolver_stock_ubicacion(r.producto_id, r.cantidad, 'Soluciones');
  END IF;

  UPDATE public.orden_taller_repuestos
  SET estado = 'solicitado',
      costo_unitario = NULL,
      aprobado_por = NULL,
      aprobado_at = NULL,
      motivo_rechazo = NULL,
      rechazado_por = NULL,
      rechazado_at = NULL
  WHERE id = p_repuesto_id;
END;
$$;
